# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - hunkon

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_d78412e19e8d478b8c92ee92b7fecd95 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_73a83eec1741417bbca24b378cd38eaa }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_d78412e19e8d478b8c92ee92b7fecd95 }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'hunkon'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_413a0c6ab6fc49469959c70a242466c7 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_d78412e19e8d478b8c92ee92b7fecd95 }}/appsvc/staticsite:${{ github.sha }}'